app/config/routes.rb
Rails.application.routes.draw do
  resources :plots
  resources :plants

  root 'plots#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/plant.rb
class Plant < ApplicationRecord
	has_many :plot_years
	has_many :plots, :through => :plot_years
end

app/app/models/plot.rb
class Plot < ApplicationRecord

	has_many :plot_years
	has_many :plants, through: :plot_years
	
end

app/app/models/plot_year.rb
class PlotYear < ApplicationRecord
  belongs_to :plot
  belongs_to :plant
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :variety, :feeder, :days_to_maturity, :season, :family, :notes, :price, :unit)
    end
end

app/app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :set_plot, only: %i[ show edit update destroy ]

  # GET /plots or /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1 or /plots/1.json
  def show
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
  end

  # POST /plots or /plots.json
  def create
    @plot = Plot.new(plot_params)

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: "Plot was successfully created." }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1 or /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: "Plot was successfully updated." }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1 or /plots/1.json
  def destroy
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: "Plot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plot
      @plot = Plot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plot_params
      params.require(:plot).permit(:sector, :lat, :long)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/plants_helper.rb
module PlantsHelper
end

app/app/helpers/plots_helper.rb
module PlotsHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :variety %>
    <%= form.text_field :variety %>
  </div>

  <div class="field">
    <%= form.label :feeder %>
    <%= form.text_field :feeder %>
  </div>

  <div class="field">
    <%= form.label :days_to_maturity %>
    <%= form.number_field :days_to_maturity %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.text_field :season %>
  </div>

  <div class="field">
    <%= form.label :family %>
    <%= form.text_field :family %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Variety</th>
      <th>Feeder</th>
      <th>Days to maturity</th>
      <th>Season</th>
      <th>Family</th>
      <th>Notes</th>
      <th>Price</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.variety %></td>
        <td><%= plant.feeder %></td>
        <td><%= plant.days_to_maturity %></td>
        <td><%= plant.season %></td>
        <td><%= plant.family %></td>
        <td><%= plant.notes %></td>
        <td><%= plant.price %></td>
        <td><%= plant.unit %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Variety:</strong>
  <%= @plant.variety %>
</p>

<p>
  <strong>Feeder:</strong>
  <%= @plant.feeder %>
</p>

<p>
  <strong>Days to maturity:</strong>
  <%= @plant.days_to_maturity %>
</p>

<p>
  <strong>Season:</strong>
  <%= @plant.season %>
</p>

<p>
  <strong>Family:</strong>
  <%= @plant.family %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @plant.notes %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plant.price %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @plant.unit %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/app/views/plots/_form.html.erb
<%= form_with(model: plot) do |form| %>
  <% if plot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plot.errors.count, "error") %> prohibited this plot from being saved:</h2>

      <ul>
        <% plot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_field :sector %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/plots/edit.html.erb
<h1>Editing Plot</h1>

<%= render 'form', plot: @plot %>

<%= link_to 'Show', @plot %> |
<%= link_to 'Back', plots_path %>

app/app/views/plots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plots</h1>


<table>
  <thead>
    <tr>
      <th>Sector</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Crop</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @plots.each do |plot| %>
      <tr>
        <td><%= plot.sector %></td>
        <td><%= plot.lat %></td>
        <td><%= plot.long %></td>
        <td><%= plot.plants.first %></td>
        <td><%= link_to 'Show', plot %></td>
        <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
        <td><%= link_to 'Destroy', plot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plot', new_plot_path %>

app/app/views/plots/new.html.erb
<h1>New Plot</h1>

<%= render 'form', plot: @plot %>

<%= link_to 'Back', plots_path %>

app/app/views/plots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sector:</strong>
  <%= @plot.sector %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @plot.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @plot.long %>
</p>

<p>
	<strong>Crop:</strong>
	<%= @plot.plants.first %>
</p>
<%= link_to 'Edit', edit_plot_path(@plot) %> |
<%= link_to 'Back', plots_path %>